-- MySQL Script generated by MySQL Workbench
-- Fri Mar 18 19:11:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema userejercicio3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema userejercicio3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userejercicio3` DEFAULT CHARACTER SET utf8 ;
USE `userejercicio3` ;

-- -----------------------------------------------------
-- Table `userejercicio3`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userejercicio3`.`usuario` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(15) NULL,
  `contra` VARCHAR(8) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
